[package]
name = "alloy-signer-azure"
description = "Ethereum Azure Key Vault signer"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--show-type-layout",
]

[lints]
workspace = true

[dependencies]
alloy-consensus = { workspace = true, features = ["std"] }
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-signer.workspace = true

async-trait.workspace = true
azure_core = "1"
azure_identity = "1"
azure_security_keyvault_keys = "1"
k256.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
eip712 = ["alloy-signer/eip712"]
