version: 2
multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: UTC
updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - '*'
    multi-ecosystem-group: weekly-dependencies
    cooldown:
      default-days: 7
  - package-ecosystem: cargo
    directory: /
    patterns:
      - '*'
    multi-ecosystem-group: weekly-dependencies
    versioning-strategy: lockfile-only
    cooldown:
      default-days: 7
