/// The constants for Multicall (deployed address + supported chains)
pub mod constants;

/// The Multicall3 contract bindings. Autogenerated with `sol!`.
pub mod contract;

/// Middleware for creating and handling multicalls
pub mod middleware;

/// Multicall specific errors
mod error;
