[package]
name = "alloy-rpc-types-txpool"
description = "Ethereum RPC txpool types"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-serde.workspace = true

serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
