[package]
name = "alloy-signer-ledger"
description = "Ethereum Ledger signer"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-consensus = { workspace = true, features = ["std"] }
alloy-primitives.workspace = true
alloy-signer.workspace = true

async-trait.workspace = true
coins-ledger = { version = "0.10", default-features = false }
futures-util.workspace = true
semver.workspace = true
thiserror.workspace = true
tracing.workspace = true

# eip712
alloy-sol-types = { workspace = true, optional = true }
alloy-network.workspace = true

[dev-dependencies]
alloy-consensus = { workspace = true, features = ["std"] }
alloy-rlp.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serial_test.workspace = true
tracing-subscriber.workspace = true

[features]
eip712 = ["alloy-signer/eip712", "dep:alloy-sol-types"]

# WASM support
browser = ["coins-ledger/browser"]
node = ["coins-ledger/node"]
