[package]
name = "alloy-signer-gcp"
description = "Ethereum GCP KMS signer"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-signer.workspace = true

async-trait.workspace = true
gcloud-sdk = { version = "0.23.1", features = [
    "google-cloud-kms-v1",
], default-features = false }
k256.workspace = true
pem = { version = "3.0.3", default-features = false }
spki.workspace = true
thiserror.workspace = true
tonic = { version = "0.10.2", default-features = false }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
eip712 = ["alloy-signer/eip712"]
