[package]
name = "alloy-rpc-types-mev"
description = "Types for the MEV JSON-RPC namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--show-type-layout",
]

[dependencies]
alloy-eips = { workspace = true, features = ["serde"] }
alloy-primitives.workspace = true
alloy-serde.workspace = true
alloy-rpc-types-eth = { workspace = true, features = ["serde"] }

serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
similar-asserts.workspace = true

[lints]
workspace = true
