[package]
name = "examples-wallets"
publish = false

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dev-dependencies]
alloy-network.workspace = true
alloy-node-bindings.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-client.workspace = true
alloy-rpc-types.workspace = true
alloy-signer = { workspace = true, features = [
    "eip712",
    "mnemonic",
    "yubihsm",
] }
alloy-signer-ledger.workspace = true
alloy-signer-trezor.workspace = true
alloy-sol-types.workspace = true
alloy-transport-http.workspace = true

rand.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
