[package]
name = "examples-wallets"
publish = false

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dev-dependencies]
alloy-rpc-client = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-network = { workspace = true }
alloy-node-bindings = { workspace = true }
alloy-primitives = { workspace = true }
alloy-providers = { workspace = true }
alloy-signer = { workspace = true, features = ["mnemonic", "yubihsm"] }
# alloy-signer-aws = { workspace = true }
# alloy-signer-gcp = { workspace = true }
alloy-signer-ledger = { workspace = true }
alloy-signer-trezor = { workspace = true }
alloy-transport-http = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
rand = { workspace = true }
