[package]
name = "alloy-transport-ipc"
description = "IPC transport implementation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-json-rpc.workspace = true
alloy-transport.workspace = true
alloy-pubsub.workspace = true

futures.workspace = true
pin-project.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["io", "compat"] }
tracing.workspace = true

bytes = "1.5.0"
interprocess = { version = "1.2.1", features = ["tokio", "tokio_support"] }
serde = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }

[dev-dependencies]
tokio-test.workspace = true

[features]
default = []
mock = ["dep:serde", "dep:tempfile"]
