[package]
name = "alloy-signers"
description = "Ethereum signer abstraction"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true

# crypto
coins-bip32 = "0.8.7"
coins-bip39 = "0.8.7"
elliptic-curve.workspace = true
k256.workspace = true
rand.workspace = true
sha2.workspace = true

# misc
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true

# futures
futures-util = { workspace = true, optional = true }

# aws
aws-config = { version = "1.0", default-features = false, optional = true }
aws-sdk-kms = { version = "0.39", default-features = false, optional = true }
spki = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
eth-keystore = "0.5.0"
home = { workspace = true, optional = true }

# ledger
coins-ledger = { version = "0.8.3", default-features = false, optional = true }
semver = { workspace = true, optional = true }

# trezor
# TODO: bump this and remove protobuf pin
trezor-client = { version = "=0.1.0", default-features = false, features = [
    "ethereum",
], optional = true }
protobuf = { version = "=3.2.0", optional = true }

# yubi
yubihsm = { version = "0.42", features = ["secp256k1", "http", "usb"], optional = true }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
yubihsm = { version = "0.42", features = ["secp256k1", "usb", "mockhsm"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
ledger = ["dep:coins-ledger", "dep:semver", "dep:futures-util"]
trezor = ["dep:trezor-client", "dep:semver", "dep:home", "dep:protobuf", "dep:futures-util"]
aws = ["dep:aws-config", "dep:aws-sdk-kms", "dep:spki"]
yubi = ["dep:yubihsm"]
