name: Seismic CI

on:
  push:
    branches: [seismic]
  pull_request:
    branches: [seismic]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"
      - name: Install SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ACTIONS_TEESERVICE_SSH_ED25519 }}
            ${{ secrets.ACTIONS_SALLOYCORE_SSH_ED25519 }}
      - name: cargo build
        run: cargo build

  warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "warnings-cache"
      - name: Install SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ACTIONS_TEESERVICE_SSH_ED25519 }}
            ${{ secrets.ACTIONS_SALLOYCORE_SSH_ED25519 }}
      - name: cargo check warnings
        run: RUSTFLAGS="-D warnings" cargo check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test-cache"
      - name: Install SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ACTIONS_TEESERVICE_SSH_ED25519 }}
            ${{ secrets.ACTIONS_SALLOYCORE_SSH_ED25519 }}
      - name: cargo test
        # Exclude crates that test connecting to local nodes
        run: cargo test --workspace
          --exclude alloy-contract
          --exclude alloy-node-bindings
          --exclude alloy-provider
          --exclude alloy-rpc-client
